### ISSUE TITLE
create metadata file for empty detection results

### ISSUE THREAD

**Issue by mkutu** [precision-sustainable-ag/Field-AnnotationPipeline#23]
detect_weeds.py is not creating a metadata file no detections. Regardless if the image has or does not have detection results, the metadata file should still be there.

**Comment by navjot-nangia** [comment]
@mkutu What should be included in this metadata file?
I have attached an example of metadata for detection.
[ALA00138.json](https://github.com/user-attachments/files/16730079/ALA00138.json)

**Comment by mkutu** [comment]
use this file as a reference. What I changed:
1. renamed "exif_meta" to "exif_info"
2. reorganized image_info
3. added plant_field_info
4. turned category into a single dictionary
5. removed username
8. removed "MasterRefID"
9. removed basename
10. renamed detection_results to annotation
11. made annotation a dictionary
12. removed image_id from annotation dictionary
13. removed class_id from annotation dictionary
14. Exif_info should contain these keys only:
ImageWidth
ImageLength
Make
Model
Software
DateTime
ExposureTime
FNumber
ExposureProgram
ISOSpeedRatings
RecommendedExposureIndex
ExifVersion
BrightnessValue
MaxApertureValue
LightSource
Flash
FocalLength
ExposureMode
WhiteBalance
FocalLengthIn35mmFilm
Contrast
Saturation
Sharpness
LensModel
LensSpecification
BodySerialNumber

15. renamed bbox to bbox_xywh (bbox coordinates need to be changed accordingly). This should be a list of values xywh

[ALA00138_updated.json](https://github.com/user-attachments/files/16732743/ALA00138_updated.json)

**Comment by navjot-nangia** [comment]
@mkutu Have you pushed these changes?

**Comment by mkutu** [comment]
@navjot-nangia I only change the file itself. I haven't changed anything.

**Comment by navjot-nangia** [comment]
DONE

**Comment by mkutu** [comment]
@navjot-nangia keep "category" even if there are not detection results

make bbox_xywh as null if there is not detection result.
```json
"annotation": {
    "bbox_xywh": null
}
```

**Comment by mkutu** [comment]
~~use this [dataclass ](https://github.com/precision-sustainable-ag/SemiF-AnnotationPipeline/blob/52556631eb0acad51f07c368057b2d4b81a49ce7/segment/semif_utils/datasets.py#L317) to format the metadata~~, and this [method ](https://github.com/precision-sustainable-ag/SemiF-AnnotationPipeline/blob/52556631eb0acad51f07c368057b2d4b81a49ce7/segment/semif_utils/datasets.py#L501)to extract it

**Comment by mkutu** [comment]
make the internal "bbox" variable in segment.py "_bbox" and write a comment or 2 to document the fact that it's internal use only

**Comment by navjot-nangia** [comment]
After using the  [method](https://github.com/precision-sustainable-ag/SemiF-AnnotationPipeline/blob/52556631eb0acad51f07c368057b2d4b81a49ce7/segment/semif_utils/datasets.py#L501), these three parameters have issue:
- exif_data: "ExifImageWidth". In the [updated json](https://github.com/user-attachments/files/16732743/ALA00138_updated.json) that you shared above: "ImageWidth". Can i just rename it?
- exif_data: "ExifImageLength". In the [updated json](https://github.com/user-attachments/files/16732743/ALA00138_updated.json) that you shared above: "ImageLength". Can i just rename it?
- I did not find any "BodySerialNumber" in the exif_data.

Other parameters are good.


The exif data from one of the images:  [exif_data.txt](https://github.com/user-attachments/files/16785603/exif_data.txt)

**Comment by mkutu** [comment]
@navjot-nangia  yea you can just rename them. I think bodyserial number only is exposed in some camera for some reason. Looks good

**Comment by navjot-nangia** [comment]
DONE
