### ISSUE TITLE
make pixel values in mask the class_id and all other pixels black

### ISSUE THREAD

**Issue by mkutu** [precision-sustainable-ag/Field-AnnotationPipeline#24]
everything that is white should be black (0) and everthing that is black should be class_id

---
![ALA00055_mask](https://github.com/user-attachments/assets/9427790e-6790-4a33-ac99-6cf4c370b729)

**Comment by navjot-nangia** [comment]
DONE

**Comment by navjot-nangia** [comment]
![MDC04122_mask](https://github.com/user-attachments/assets/45c721eb-dcbb-4bf4-8a93-ff0aed1ed91f)

**Comment by navjot-nangia** [comment]
DONE
