### ISSUE TITLE
species_info update

### ISSUE THREAD

**Issue by navjot-nangia** [precision-sustainable-ag/Field-AnnotationPipeline#25]
- Added new species in annotation pipeline repo. 
- Need to check and make sure the entries are correct
- Need to coorect location, # hex etc for Copperleaf (ACOS)

**Comment by mkutu** [comment]
@navjot-nangia add an "alias" key to times when there are more than one common_name
and use the true common_name, not the alias, in later metadata versions.

**Comment by mkutu** [comment]
@mkutu review Nav's species_info.json file for accuracy
