### ISSUE TITLE
implement detection model in pipeline using hydra

### ISSUE THREAD

**Issue by mkutu** [precision-sustainable-ag/Field-AnnotationPipeline#6]
implement detection model in overall pipeline by using standard hydra config format that we've been using fro SemiF-AnnotationPipeline and Field-DataExploration

**Comment by mkutu** [comment]
create the 4 main outputs as discussed: 
1. cropout
2. cutout
3. cutout mask
4. cutout metadata (this can be simplified)

**Comment by navjot-nangia** [comment]
Being taken care in other issue.
